Issue 7
oracle-terraform-modules/terraform-oci-ocne pull request #9
Opened 2020-06-05 02:55 UTC by hyder

* Upgraded base module to 1.2.2
* Use operator from base module as olcne operator
* Set default networking parameters and removed redundant variables
* Upgraded Oracle Linux version to 7.8
* Added support for new regions (Hyderabad and Chuncheon)
* Added terraformoptions to documentation
* Added README.md for HashiCorp registry
* Removed default backend on nginxcontroller

2020-06-07 21:09 UTC, Djelibeybi commented
Resolves #7

2020-06-08 23:00 UTC, Djelibeybi requested changes

2020-06-08 23:00 UTC, Djelibeybi commented on README.md
> +- Select one of the {uri-oci-bmshapes}[Bare Metal shapes] for your worker nodes.
Need to change {} to () for Markdown to render the link.

2020-06-08 23:00 UTC, Djelibeybi commented on datasources.tf
> +# data "oci_identity_availability_domains" "ad_list" {
Is there a reason why all these data sources appear to be commented out? If they're meant to be enabled by the end-user, having a brief description for each and when they should be enabled within the file would be useful to those who refuse to RTFREADME. :)

2020-06-08 23:00 UTC, Djelibeybi commented on docs/prerequisites.adoc
> +. manage dynamic groups
You're using `.` here, but `1.` for the numbering lower in the same file. It would be better to stick to a single standard for numbered list generation.

2020-06-08 23:00 UTC, Djelibeybi commented on docs/prerequisites.adoc
> +1. Open your browser and navigate to the {uri-terraform-download}[Terraform download page]. You need version 0.12.16+.
Why are you not using the `.` style for numbered list generation here?

2020-06-08 23:00 UTC, Djelibeybi commented on docs/terraformoptions.adoc
> +|api_fingerprint
The actual variable names like `api_fingerprint` in the first column should be rendered in monospace.

2020-06-08 23:00 UTC, Djelibeybi commented on docs/terraformoptions.adoc
> +|Region where to provision the OLCNE cluster. {uri-oci-region}[List of regions]. *Required*
I would move the **required** vs **optional** marker to a dedicated column so it's easier to see.

2020-06-09 00:25 UTC, hyder commented on README.md
> +- Select one of the {uri-oci-bmshapes}[Bare Metal shapes] for your worker nodes.
fixed.

2020-06-09 00:26 UTC, hyder commented on datasources.tf
> +# data "oci_identity_availability_domains" "ad_list" {
remnant of before switching to the new base module. deleted them.

2020-06-09 00:33 UTC, hyder commented on docs/terraformoptions.adoc
> +|api_fingerprint
fixed

2020-06-09 00:34 UTC, hyder commented on docs/prerequisites.adoc
> +1. Open your browser and navigate to the {uri-terraform-download}[Terraform download page]. You need version 0.12.16+.
fixed

2020-06-09 00:34 UTC, hyder commented on docs/terraformoptions.adoc
> +|Region where to provision the OLCNE cluster. {uri-oci-region}[List of regions]. *Required*
great idea. I'll adopt this in all repos going forward.

2020-06-11 00:47 UTC, mark-au requested changes
On top of the recommendations made the code does not pass a `terraform apply`

If using `bastion_image_id = "Autonomous"` as per example in terraform.tfvars.example
```
Error: Invalid index

  on .terraform\modules\base.bastion\terraform-oci-bastion-1.0.1\locals.tf line 13, in locals:
  13:   bastion_image_id = var.bastion_image_id == "Autonomous" ? data.oci_core_images.autonomous_images.images.0.id : var.bastion_image_id
    |----------------
    | data.oci_core_images.autonomous_images.images is empty list of object

The given key does not identify an element in this collection value.
```

If I change this to `bastion_image_id = "Oracle Autonomous"` I receive
```

Error: Invalid index

  on .terraform\modules\base.bastion\terraform-oci-bastion-1.0.1\datasources.tf line 67, in data "template_cloudinit_config" "bastion":
  67:     content      = data.template_file.autonomous_cloud_init_file[0].rendered
    |----------------
    | data.template_file.autonomous_cloud_init_file is empty tuple

The given key does not identify an element in this collection value.
```
Let me know when this is resolved

2020-06-11 00:47 UTC, mark-au commented on terraform.tfvars.example
> +  operator = 1
Appears to unnecessary duplicate key/value pair

2020-06-11 00:47 UTC, mark-au commented on variables.tf
> +    operator = 1
Appears to unnecessary duplicate key/value pair

2020-06-11 00:47 UTC, mark-au commented on modules/network/outputs.tf
> +    # "operator", join(",", oci_core_subnet.operator.*.id)
Why's the operator subnet commented after this change? I don't think it exists anymore (see below) so it'd be good to remove it

2020-06-11 00:47 UTC, mark-au commented on modules/network/subnets.tf
> +# resource "oci_core_subnet" "operator" {
Why not remove the subnet instead of commenting it out?

2020-06-11 00:47 UTC, mark-au commented on modules/olcne/outputs.tf
Delete empty file?

2020-06-11 00:47 UTC, mark-au commented on modules/worker/scripts/worker.template.sh
> -# ol7_UEKR5
Why don't we enable ol7_UEKR5?

2020-06-11 00:47 UTC, mark-au commented on README.md
> +- In terraform.tfvars, enable only the bastion host:
You've removed this var

2020-06-11 00:47 UTC, mark-au commented on terraform.tfvars.example
> +operator_notification_enabled = false
These values are redeclared on lines 115+ causing errors

2020-06-11 23:55 UTC, mark-au approved these changes

2020-06-11 23:55 UTC, mark-au commented
I don't have the dynamic-groups to spare to test this deployment but I can confirm deployment begins and thanks for resolving the issues I mentioned.

2020-06-12 06:39 UTC, merged